version: '3.8'

services:
  # 前端应用服务
  resume-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: resume-editor
    ports:
      - "3333:80"
    environment:
      - NODE_ENV=production
    volumes:
      # 可选：挂载日志目录
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - resume-network

  # 可选：添加反向代理（生产环境推荐）
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: resume-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - resume-app
    restart: unless-stopped
    networks:
      - resume-network
    profiles:
      - proxy

  # 可选：监控服务
  portainer:
    image: portainer/portainer-ce:latest
    container_name: resume-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - resume-network
    profiles:
      - monitoring

networks:
  resume-network:
    driver: bridge

volumes:
  portainer_data: 