version: '3.8'

services:
  # 前端应用服务
  resume-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: resume-editor-prod
    ports:
      - "3333:80"
    environment:
      - NODE_ENV=production
    volumes:
      # 日志目录挂载
      - ./logs:/var/log/nginx
      # 可选：挂载自定义nginx配置
      # - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - resume-network
    labels:
      - "app=resume-editor"
      - "env=production"
      - "version=latest"

networks:
  resume-network:
    driver: bridge
    name: resume-network

volumes:
  logs:
    driver: local 